apiVersion: v1
kind: Service
metadata:
  name: mypod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123
  selector:
    run: mypod

---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: 966145/myimg:tagVersion
    name: mypod
    ports:
    - containerPort: 80
